export const SWITCH_CURRENCIES = "SWITCH_CURRENCIES";
export const CHANGE_AMOUNT = "CHANGE_AMOUNT";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const SET_RATES = 'SET_RATES';
export const CALCULATE_CURRENCY = 'CALCULATE_CURRENCY';